
env: city_navigation

test_greedy: True
test_nepisode: 100
test_interval: 500
log_interval: 500
runner_log_interval: 500
learner_log_interval: 500
t_max:  50000



env_args:
  map_name: very_small_map
  n_persons: 2
  speed: 400
  episode_limit: 100

